name: Daily Weather Script

on:
  schedule:
    - cron: '45 11 * * *'  # Runs at 11:45 AM UTC every day
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  run-weather-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make script executable
        run: chmod u+x ./weather.sh # not strictly necessary

      - name: Random sleep
        run: |
          RANDOM_SLEEP=$((RANDOM % 21)) # 0-20 minutes
          echo "Sleeping for $RANDOM_SLEEP minutes..."
          SLEEP_TIME=$((RANDOM_SLEEP * 60)) # convert to minutes
          sleep $SLEEP_TIME
          echo "Awake! Running the shell script now."

      - name: Run weather script
        run: ./weather.sh

      - name: Configure Git
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
      - name: Commit changes
        run: |
          git add .
          git commit -m "Update daily weather data" || echo "No changes to commit"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin HEAD
