name: Daily Weather Script

on:
  schedule:
    - cron: '0 10 * * *'  # Runs at 10 AM UTC every day
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  run-weather-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make script executable
        run: chmod u+x ./weather_updated.sh

      - name: Run weather script
        run: ./weather_updated.sh

      - name: Configure Git
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
      - name: Commit changes
        run: |
          git add .
          git commit -m "Update daily weather data" || echo "No changes to commit"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin HEAD
