name: Daily Weather Script

on:
  schedule:
    - cron: '0 10 * * *'  # Runs at 10 AM UTC every day
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  run-weather-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make script executable
        run: chmod +x ./weather.sh

      - name: Run weather script
        run: ./weather.sh
